doks:
    baseurl:
    color_theme: blue
    micro_nav:
    - title: macOS
      url: '/'


    header:
        logo:
            text:
            image: true
        nav:
            - item_name: Documentation
              item_url: https://icons8.com/docs
            - item_name: Plugins
              item_url: https://icons8.com/app/figma
              external_url: true
            - item_name: Icons
              item_url: https://icons8.com
              external_url: true
            - item_name: Blog
              item_url: https://blog.icons8.com
              external_url: true
            - item_name: Forum
              item_url: https://community.icons8.com
              external_url: true


    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/

algolia:
  application_id: E0SRZV1KDE
  index_name: docs_pichon_macos
  search_only_api_key: 3c69946746f91017d9d59e85186f93ea
  files_to_exclude: []
